// Code generated by scripts/generate-skill-config-contract.mjs; DO NOT EDIT.
// 此文件由 scripts/generate-skill-config-contract.mjs 生成；请勿手工编辑。

/**
 * Contract version emitted by the matching LuaSkills core release.
 * 与当前 SDK 匹配的 LuaSkills 核心版本所生成的契约版本。
 */
export const SKILL_CONFIG_CONTRACT_VERSION = 1 as const;

/**
 * Declared package-configuration scalar types.
 * 已声明技能包配置的标量类型。
 */
export const SKILL_PACKAGE_CONFIG_TYPES = [
  "integer",
  "string",
  "float",
  "enum",
  "boolean",
] as const;

/**
 * Supported host rendering formats for string declarations.
 * 字符串声明支持的宿主渲染格式。
 */
export const SKILL_PACKAGE_CONFIG_FORMATS = [
  "text",
  "password",
  "uri",
  "path",
  "file",
  "directory",
  "multiline",
] as const;

/**
 * Stable effective-value states.
 * 稳定的有效值状态。
 */
export const SKILL_PACKAGE_CONFIG_STATES = [
  "unset",
  "missing",
  "default",
  "configured",
  "invalid",
] as const;

/**
 * Stable package-configuration declaration discovery modes.
 * 稳定的技能包配置声明发现模式。
 */
export const SKILL_PACKAGE_CONFIG_DESCRIBE_MODES = [
  "effective",
  "installed",
] as const;

/**
 * Stable package-configuration declaration discovery mode.
 * 稳定的技能包配置声明发现模式。
 */
export type SkillPackageConfigDescribeMode =
  (typeof SKILL_PACKAGE_CONFIG_DESCRIBE_MODES)[number];

/**
 * Stable package-configuration store scopes.
 * 稳定的技能包配置存储作用域。
 */
export const SKILL_CONFIG_STORE_SCOPES = [
  "skills",
  "system-skills",
] as const;

/**
 * Stable package-configuration store scope.
 * 稳定的技能包配置存储作用域。
 */
export type SkillConfigStoreScope = (typeof SKILL_CONFIG_STORE_SCOPES)[number];

/**
 * Stable machine-readable package-configuration error codes.
 * 稳定的机器可读技能包配置错误码。
 */
export const SKILL_CONFIG_ERROR_CODES = [
  "CONFIG_ATOMIC_REPLACE_FAILED",
  "CONFIG_BATCH_ARGUMENT_CONFLICT",
  "CONFIG_BATCH_EMPTY",
  "CONFIG_BATCH_TOO_LARGE",
  "CONFIG_DECLARATION_INVALID",
  "CONFIG_ENUM_VALUE_INVALID",
  "CONFIG_EVENT_CURSOR_EXPIRED",
  "CONFIG_EVENT_CURSOR_INVALID",
  "CONFIG_FILE_TOO_LARGE",
  "CONFIG_FORMAT_INVALID",
  "CONFIG_FORMAT_VERSION_UNSUPPORTED",
  "CONFIG_KEY_INVALID",
  "CONFIG_KEY_UNDECLARED",
  "CONFIG_LOCK_FAILED",
  "CONFIG_LOCK_TIMEOUT",
  "CONFIG_PACKAGE_NOT_FOUND",
  "CONFIG_PATH_INVALID",
  "CONFIG_PATH_UNAVAILABLE",
  "CONFIG_RELOAD_FAILED",
  "CONFIG_RESPONSE_TOO_LARGE",
  "CONFIG_REVISION_CONFLICT",
  "CONFIG_REVISION_EXHAUSTED",
  "CONFIG_REVISION_INVALID",
  "CONFIG_REVISION_REGRESSION",
  "CONFIG_SNAPSHOT_UNAVAILABLE",
  "CONFIG_VALIDATOR_FAILED",
  "CONFIG_VALIDATOR_LIMIT_EXCEEDED",
  "CONFIG_VALIDATOR_TIMEOUT",
  "CONFIG_VALIDATOR_UNAVAILABLE",
  "CONFIG_VALUE_OUT_OF_RANGE",
  "CONFIG_VALUE_TOO_LONG",
  "CONFIG_VALUE_TYPE_INVALID",
  "CONFIG_WATCHER_FAILED",
] as const;

/**
 * Stable machine-readable package-configuration error code.
 * 稳定的机器可读技能包配置错误码。
 */
export type SkillConfigErrorCode = (typeof SKILL_CONFIG_ERROR_CODES)[number];

/**
 * Largest exactly representable integer shared by every supported SDK.
 * 所有受支持 SDK 共同精确表示的最大整数。
 */
export const SKILL_CONFIG_MAXIMUM_SAFE_INTEGER = 9_007_199_254_740_991;

/**
 * Largest event page accepted by the core contract.
 * 核心契约允许的最大事件分页大小。
 */
export const SKILL_CONFIG_MAXIMUM_EVENT_POLL_LIMIT = 1_024;
