/**
 * Generated wire shape for embedded contract.
 * embedded contract 的生成线形状。
 */
// Generated by scripts/generate-embedded-contract.mjs; do not edit.
// 由 scripts/generate-embedded-contract.mjs 生成；请勿编辑。

import type { EmbeddedFloat } from "./embedded-value.js";

/** Exact integer inputs use bigint outside the safe number range.
 * 超出安全 number 范围的精确整数输入使用 bigint。 */
export type EmbeddedInteger = number | bigint;

/** Recursive JSON values with lossless integers and explicit float intent.
 * 具有无损整数和显式浮点意图的递归 JSON 值。 */
export type EmbeddedJsonValue = null | boolean | string | number | bigint | EmbeddedFloat | EmbeddedJsonValue[] | { [key: string]: EmbeddedJsonValue };

/**
 * Generated wire shape for EMBEDDED_PROTOCOL_VERSION.
 * EMBEDDED_PROTOCOL_VERSION 的生成线形状。
 */
export const EMBEDDED_PROTOCOL_VERSION = 1 as const;

/**
 * Generated wire shape for EMBEDDED_CONTRACT_VERSION.
 * EMBEDDED_CONTRACT_VERSION 的生成线形状。
 */
export const EMBEDDED_CONTRACT_VERSION = 1 as const;

/**
 * Generated wire shape for EMBEDDED_CORE_VERSION.
 * EMBEDDED_CORE_VERSION 的生成线形状。
 */
export const EMBEDDED_CORE_VERSION = "0.5.9" as const;

/**
 * Generated wire shape for EMBEDDED_CONTRACT_SHA256.
 * EMBEDDED_CONTRACT_SHA256 的生成线形状。
 */
export const EMBEDDED_CONTRACT_SHA256 = "e85a237140e8d6d761b69d3bde97e05e290630eec463f1127c4a6a2b7ef888fc" as const;

/**
 * Generated wire shape for EMBEDDED_ROOT_COMMANDS.
 * EMBEDDED_ROOT_COMMANDS 的生成线形状。
 */
export const EMBEDDED_ROOT_COMMANDS = Object.freeze(["describe","runtime_reserve","runtime_initialize","runtime_status","runtime_close","runtime_free","runtime"] as const);

/**
 * Generated wire shape for EMBEDDED_RUNTIME_COMMANDS.
 * EMBEDDED_RUNTIME_COMMANDS 的生成线形状。
 */
export const EMBEDDED_RUNTIME_COMMANDS = Object.freeze(["plugin_register","plugin_status","plugin_close","plugin_forget","pool_register","pool_status","pool_close","pool_forget","pool_revoke_permission","call_submit","session_open","session_submit","session_status","session_close","session_forget","operation_status","operation_wait","operation_cancel","operation_forget","capabilities_register","capabilities_list","capability_status","capability_unregister","capability_forget","host_requests_take","host_request_status","host_request_complete"] as const);

/**
 * Generated wire shape for EMBEDDED_DESCRIPTION_VERSION.
 * EMBEDDED_DESCRIPTION_VERSION 的生成线形状。
 */
export const EMBEDDED_DESCRIPTION_VERSION = 1 as const;

/**
 * Generated wire shape for EMBEDDED_DESCRIPTION_MAX_BYTES.
 * EMBEDDED_DESCRIPTION_MAX_BYTES 的生成线形状。
 */
export const EMBEDDED_DESCRIPTION_MAX_BYTES = 16384 as const;

/**
 * Generated wire shape for EMBEDDED_REQUIRED_CAPABILITIES.
 * EMBEDDED_REQUIRED_CAPABILITIES 的生成线形状。
 */
export const EMBEDDED_REQUIRED_CAPABILITIES = Object.freeze(["bounded_transports_v1","plugin_budgets_v1","shared_pools_v1","dedicated_pools_v1","fixed_sessions_v1","host_request_queue_v1","in_memory_effect_evidence_v1","strict_json_v1"] as const);

/**
 * Generated wire shape for EmbeddedNativeStatus.
 * EmbeddedNativeStatus 的生成线形状。
 */
export enum EmbeddedNativeStatus {
/**
 * Generated wire shape for ok.
 * ok 的生成线形状。
 */
OK = 0,
/**
 * Generated wire shape for invalid_argument.
 * invalid_argument 的生成线形状。
 */
INVALID_ARGUMENT = 1,
/**
 * Generated wire shape for not_found.
 * not_found 的生成线形状。
 */
NOT_FOUND = 2,
/**
 * Generated wire shape for busy.
 * busy 的生成线形状。
 */
BUSY = 3,
/**
 * Generated wire shape for capacity_exceeded.
 * capacity_exceeded 的生成线形状。
 */
CAPACITY_EXCEEDED = 4,
/**
 * Generated wire shape for closed.
 * closed 的生成线形状。
 */
CLOSED = 5,
/**
 * Generated wire shape for internal.
 * internal 的生成线形状。
 */
INTERNAL = 6,
/**
 * Generated wire shape for unsupported.
 * unsupported 的生成线形状。
 */
UNSUPPORTED = 7,
}

// Native codes are immutable runtime metadata as well as compile-time names.
// 原生状态码既是编译期名称，也是不可变运行时元数据。
Object.freeze(EmbeddedNativeStatus);

/**
 * Immutable capability declaration shared by Rust, generated contracts and SDKs.
 * Rust、生成契约与 SDK 共享的不可变能力声明。
 */
export type InputCapabilityDescriptor = ({
/**
 * English description of the host capability for tool consumers.
 * 面向工具消费者的宿主能力英文描述。
 */
"description": string;
/**
 * Declared mutation category.
 * 声明的变更类别。
 */
"effects": InputCapabilityEffects;
/**
 * Explicit native or queued dispatch protocol.
 * 显式原生或队列分发协议。
 */
"execution": InputCapabilityExecution;
/**
 * Explicit host deduplication contract.
 * 显式宿主去重契约。
 */
"idempotency": InputCapabilityIdempotency;
/**
 * Offline input value contract.
 * 离线输入值契约。
 */
"input_schema": EmbeddedJsonValue;
/**
 * Per-capability budget capped by the original operation deadline.
 * 受原始操作截止时间约束的单能力预算。
 */
"max_call_ms": EmbeddedInteger;
/**
 * Maximum in-flight handlers, including cancelled handlers that have not stopped.
 * 在途处理器上限，包含已取消但尚未停止的处理器。
 */
"max_concurrent": EmbeddedInteger;
/**
 * Maximum serialized input bytes within the parent value limit.
 * 父级值上限内的最大序列化输入字节数。
 */
"max_input_bytes": EmbeddedInteger;
/**
 * Maximum serialized output bytes within the parent value limit.
 * 父级值上限内的最大序列化输出字节数。
 */
"max_output_bytes": EmbeddedInteger;
/**
 * Exact namespaced name; discovery exposes only authorized declarations.
 * 精确命名空间名称；发现操作仅暴露已授权声明。
 */
"name": string;
/**
 * Offline output value contract.
 * 离线输出值契约。
 */
"output_schema": EmbeddedJsonValue;
/**
 * Every listed grant must still exist at each admission boundary.
 * 每个入场边界仍必须拥有列出的全部授权。
 */
"permissions": Array<string>;
/**
 * Required trusted invocation scope.
 * 必需的可信调用作用域。
 */
"scope": InputCapabilityScope;
/**
 * Semantic interface version, independent from the core library version.
 * 语义接口版本，独立于核心库版本。
 */
"version": string;
});

/**
 * Declared effect category; it does not make external mutations transactional.
 * 声明的副作用类别；它不会使外部变更自动具有事务性。
 */
export type InputCapabilityEffects = ("read_only" | "mutating");

/**
 * Host execution transport, explicitly selected before a capability is published.
 * 宿主执行传输，在能力发布前显式选择。
 */
export type InputCapabilityExecution = ("native" | "queued");

/**
 * Explicit side-effect deduplication support, never inferred from an operation identifier.
 * 显式副作用去重支持，绝不从操作标识推断。
 */
export type InputCapabilityIdempotency = ("none" | "host_request");

/**
 * Scope required from the trusted caller, independent from Lua business arguments.
 * 可信调用方必须具备的作用域，独立于 Lua 业务参数。
 */
export type InputCapabilityScope = ("invocation" | "session");

/**
 * Implemented commands only; new runtime commands are advertised when actually wired.
 * 仅包含已实现命令；新的运行时命令在实际接通后才公布。
 */
export type InputCommand = (({
/**
 * Typed core operation with no legacy command aliases.
 * 不含旧命令别名的类型化核心操作。
 */
"operation": InputRuntimeCommand;
/**
 * Exact transport-local runtime identity.
 * 精确传输局部运行时身份。
 */
"runtime_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime";
}) | ({
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "describe";
}) | ({
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime_reserve";
}) | ({
/**
 * Explicit core engine options, using the existing engine option contract.
 * 显式核心引擎选项，使用现有引擎选项契约。
 */
"engine_options": InputLuaEngineOptions;
/**
 * Explicit formal runtime budgets validated before worker construction.
 * 工作线程构造前校验的显式正式运行时预算。
 */
"runtime_config": InputEmbeddedRuntimeConfig;
/**
 * Exact identity returned by runtime_reserve in this transport.
 * 此传输中 runtime_reserve 返回的精确身份。
 */
"runtime_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime_initialize";
}) | ({
/**
 * Exact retained runtime identity in this transport.
 * 此传输中保留的精确运行时身份。
 */
"runtime_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime_status";
}) | ({
/**
 * Exact retained runtime identity in this transport.
 * 此传输中保留的精确运行时身份。
 */
"runtime_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime_close";
}) | ({
/**
 * Exact retained runtime identity in this transport.
 * 此传输中保留的精确运行时身份。
 */
"runtime_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "runtime_free";
}));

/**
 * Host-reported effect outcome, independent from execution success or cancellation.
 * 宿主报告的副作用结果，独立于执行成功或取消。
 */
export type InputEffectState = ("not_started" | "not_applicable" | "committed" | "rolled_back" | "unknown");

/**
 * Owned structured request admitted under one original deadline.
 * 在单个原始截止时间下接纳的拥有所有权的结构化请求。
 */
export type InputEmbeddedCall = ({
/**
 * Application value whose encoded size is checked before admission.
 * 入场前检查编码大小的应用值。
 */
"arguments": EmbeddedJsonValue;
/**
 * Trusted host context retained and charged with the queued request.
 * 与排队请求一并保留和计费的可信宿主上下文。
 */
"context": InputLuaInvocationContext;
/**
 * Exact declared module export, never an evaluated code fragment.
 * 精确声明的模块导出，绝不是求值代码片段。
 */
"export": string;
/**
 * Exact immutable pool identity returned by this runtime.
 * 此运行时返回的精确不可变池身份。
 */
"pool_id": string;
});

/**
 * Structured error; `code` is stable and `message` is an English diagnostic.
 * 结构化错误；`code` 稳定，`message` 为英文诊断信息。
 */
export type InputEmbeddedError = ({
/**
 * Stable classification consumed by SDKs instead of parsing text.
 * 供 SDK 使用的稳定分类，避免解析文案。
 */
"code": InputEmbeddedErrorCode;
/**
 * Human-readable detail without credentials or plugin input dumps.
 * 不含凭据或插件输入转储的可读详情。
 */
"message": string;
});

/**
 * Stable machine-readable failures shared by Rust and the versioned FFI protocol.
 * Rust 与版本化 FFI 协议共享的稳定机器可读错误。
 */
export type InputEmbeddedErrorCode = ("invalid_argument" | "not_found" | "stale_generation" | "capacity_exceeded" | "busy" | "already_completed" | "closed" | "cancelled" | "deadline_exceeded" | "permission_denied" | "unsupported" | "execution_failed" | "cleanup_failed" | "internal");

/**
 * Immutable host-approved aggregate budgets across every generation and execution domain of one plugin.
 * 一个插件的全部代次与执行域共享的不可变宿主批准聚合预算。
 */
export type InputEmbeddedPluginConfig = ({
/**
 * Maximum retained operations, including completed results not explicitly forgotten.
 * 保留操作的数量上限，包含尚未显式遗忘的已完成结果。
 */
"max_operations": EmbeddedInteger;
/**
 * Maximum exact serialized queued request bytes across this plugin.
 * 此插件全部排队请求精确序列化字节数上限。
 */
"max_queued_bytes": EmbeddedInteger;
/**
 * Maximum accepted queued calls across all domains and sessions.
 * 全部域和会话已接纳排队调用的合计上限。
 */
"max_queued_calls": EmbeddedInteger;
/**
 * Maximum retained pool identities, including closed generations awaiting explicit removal.
 * 保留池身份的数量上限，包含等待显式移除的已关闭代次。
 */
"max_registered_pools": EmbeddedInteger;
/**
 * Maximum actual resident VMs plus other domains' unused dedicated reservations.
 * 实际常驻 VM 与其他域未使用专用预留的合计上限。
 */
"max_resident_vms": EmbeddedInteger;
/**
 * Maximum dispatched operations, retained through initialization, host waiting and cleanup.
 * 已分发操作上限，计费覆盖初始化、宿主等待及清理。
 */
"max_running_calls": EmbeddedInteger;
/**
 * Maximum retained sessions, including closed session records.
 * 保留会话的数量上限，包含已关闭会话记录。
 */
"max_sessions": EmbeddedInteger;
});

/**
 * Explicit parent budgets; hosts resolve defaults once before construction.
 * 显式父级预算；宿主在构造前一次性解析默认值。
 */
export type InputEmbeddedRuntimeConfig = ({
/**
 * Maximum serialized module context and effect metadata bytes retained by one operation.
 * 单次操作保留的模块上下文及副作用元数据序列化字节上限。
 */
"max_effect_bytes_per_operation": EmbeddedInteger;
/**
 * Maximum host effect records retained by one operation, including completed callbacks.
 * 单次操作保留的宿主副作用记录上限，包含已完成回调。
 */
"max_effect_records_per_operation": EmbeddedInteger;
/**
 * Maximum request bytes and reserved application output bytes, including dispatched calls.
 * 请求字节与预留应用输出字节上限，包含已分发调用。
 * Fixed protocol error metadata is separately bounded by the retained request count.
 * 固定协议错误元数据由保留请求数量独立约束。
 */
"max_host_request_bytes": EmbeddedInteger;
/**
 * Maximum pending host requests across all plugin instances.
 * 所有插件实例待完成宿主请求的数量上限。
 */
"max_host_requests": EmbeddedInteger;
/**
 * Maximum operation records retained, including unfinished operations.
 * 操作记录保留数量上限，包含未完成操作。
 */
"max_operations": EmbeddedInteger;
/**
 * Maximum serialized bytes retained by queued requests.
 * 排队请求保留的序列化字节数上限。
 */
"max_queued_bytes": EmbeddedInteger;
/**
 * Maximum accepted requests waiting for an execution slot.
 * 等待执行许可的已接纳请求数量上限。
 */
"max_queued_calls": EmbeddedInteger;
/**
 * Maximum retained capability registrations, including draining or unforgotten retired entries.
 * 能力注册保留上限，包含正在排空或尚未遗忘的已退役条目。
 */
"max_registered_capabilities": EmbeddedInteger;
/**
 * Maximum retained plugin registrations, including closed entries awaiting explicit removal.
 * 保留插件注册的数量上限，包含等待显式移除的已关闭条目。
 */
"max_registered_plugins": EmbeddedInteger;
/**
 * Maximum concurrently registered pool declarations, including draining generations.
 * 同时注册的池声明数量上限，包含正在排空的代次。
 */
"max_registered_pools": EmbeddedInteger;
/**
 * Maximum resident VMs, including creation and pending teardown.
 * 最大常驻 VM 数，包含创建中与等待清理的实例。
 */
"max_resident_vms": EmbeddedInteger;
/**
 * Maximum concurrent calls, including calls waiting for host results.
 * 最大并发调用数，包含等待宿主结果的调用。
 */
"max_running_calls": EmbeddedInteger;
/**
 * Maximum retained session identities, including closed sessions awaiting explicit removal.
 * 保留会话身份的数量上限，包含等待显式移除的已关闭会话。
 */
"max_sessions": EmbeddedInteger;
/**
 * Maximum serialized application value bytes; fixed protocol error metadata is separate.
 * 应用值的最大序列化字节数；固定协议错误元数据独立计算。
 */
"max_value_bytes": EmbeddedInteger;
});

/**
 * Declared backend; unavailable variants are rejected instead of downgraded.
 * 声明的执行后端；不可用的取值直接拒绝，不降级。
 */
export type InputExecutionBackend = ("in_process" | "worker_process");

/**
 * Strict host completion shapes match CapabilityOutcome::to_json, preserving successful JSON null.
 * 严格宿主完成形状匹配 CapabilityOutcome::to_json，保留成功 JSON 空值。
 */
export type InputHostCompletion = (({
/**
 * Actual host effect evidence.
 * 实际宿主副作用证据。
 */
"effects": InputEffectState;
/**
 * Explicit success discriminator.
 * 显式成功判别。
 */
"ok": boolean;
/**
 * Actual application result.
 * 实际应用结果。
 */
"value": EmbeddedJsonValue;
}) | ({
/**
 * Actual host effect evidence, even if a commit preceded the error.
 * 实际宿主副作用证据，即使错误前已发生提交。
 */
"effects": InputEffectState;
/**
 * Actual structured host error.
 * 实际结构化宿主错误。
 */
"error": InputEmbeddedError;
/**
 * Explicit failure discriminator.
 * 显式失败判别。
 */
"ok": boolean;
}));

/**
 * Explicit module-state lifetime selected by a validated plugin contract.
 * 由已校验插件契约选择的显式模块状态寿命。
 */
export type InputInstanceReuse = ("single_call" | "reusable" | "session");

/**
 * Construction options used by the host to create one LuaSkills runtime engine.
 * 宿主创建单个 LuaSkills 运行时引擎时使用的构造选项。
 */
export type InputLuaEngineOptions = ({
/**
 * Host-owned runtime paths and external library locations.
 * 宿主拥有的运行时路径与外部动态库位置配置。
 */
"host_options": InputLuaRuntimeHostOptions;
/**
 * Pool sizing configuration for reusable Lua virtual machines.
 * 可复用 Lua 虚拟机池的容量配置。
 */
"pool_config": InputLuaVmPoolConfig;
} & Record<string, EmbeddedJsonValue>);

/**
 * Host-injected invocation context delivered alongside one skill or runlua call.
 * 宿主在单次 skill 或 runlua 调用时一并注入的调用上下文。
 */
export type InputLuaInvocationContext = ({
/**
 * Host-resolved client budget object injected into `vulcan.context.client_budget`.
 * 宿主解析后的客户端预算对象，将被注入到 `vulcan.context.client_budget`。
 */
"client_budget": EmbeddedJsonValue;
/**
 * Optional transport/request metadata preserved for Lua consumption.
 * 供 Lua 消费的可选传输层/请求层元数据。
 */
"request_context"?: (InputRuntimeRequestContext | null);
/**
 * Host-resolved tool configuration object injected into `vulcan.context.tool_config`.
 * 宿主解析后的工具配置对象，将被注入到 `vulcan.context.tool_config`。
 */
"tool_config": EmbeddedJsonValue;
} & Record<string, EmbeddedJsonValue>);

/**
 * Host-controlled toggles for optional Lua-exposed runtime bridges.
 * 宿主控制的可选 Lua 暴露运行时桥接开关集合。
 */
export type InputLuaRuntimeCapabilityOptions = ({
/**
 * Whether luaexec and runtime sessions replace Lua's global `io` table with managed IO.
 * luaexec 与持久运行时会话是否使用托管 IO 替换 Lua 全局 `io` 表。
 */
"enable_managed_io_compat": boolean;
/**
 * Whether `vulcan.runtime.skills.*` management bridges are exposed to Lua.
 * 是否将 `vulcan.runtime.skills.*` 管理桥接暴露给 Lua。
 */
"enable_skill_management_bridge"?: boolean;
} & Record<string, EmbeddedJsonValue>);

/**
 * Callback transport mode used when the database provider mode is `host_callback`.
 * 当数据库 provider 模式为 `host_callback` 时所使用的回调传输模式。
 */
export type InputLuaRuntimeDatabaseCallbackMode = ("standard" | "json");

/**
 * Database access mode used by one host-facing runtime backend.
 * 单个宿主侧运行时后端所使用的数据库访问模式。
 */
export type InputLuaRuntimeDatabaseProviderMode = ("dynamic_library" | "host_callback" | "space_controller");

/**
 * Host-provided filesystem and runtime paths consumed by the LuaSkills library.
 * 宿主提供给 LuaSkills 库消费的文件系统与运行时路径集合。
 */
export type InputLuaRuntimeHostOptions = ({
/**
 * Whether the runtime is allowed to perform network downloads while installing dependencies.
 * 运行时在安装依赖时是否允许执行网络下载。
 */
"allow_network_download": boolean;
/**
 * Host-provided transient cache policy consumed by `vulcan.cache`.
 * 由宿主提供并供 `vulcan.cache` 消费的临时缓存策略。
 */
"cache_config"?: (InputToolCacheConfig | null);
/**
 * Host-controlled optional runtime capability toggles.
 * 由宿主控制的可选运行时能力开关集合。
 */
"capabilities"?: InputLuaRuntimeCapabilityOptions;
/**
 * Fixed sibling directory name used under one skill-root parent to store skill databases.
 * 在单个技能根父目录下存放技能数据库时使用的固定兄弟目录名称。
 */
"database_dir_name"?: string;
/**
 * Optional default text encoding label used by managed IO and process APIs.
 * 托管 IO 与进程 API 使用的可选默认文本编码标签。
 */
"default_text_encoding"?: (string | null);
/**
 * Fixed sibling directory name used under one skill-root parent to store dependencies.
 * 在单个技能根父目录下存放依赖时使用的固定兄弟目录名称。
 */
"dependency_dir_name"?: string;
/**
 * Host-managed cache directory used for downloaded archives and remote manifests.
 * 宿主管理的下载缓存目录，用于归档文件和远程清单缓存。
 */
"download_cache_root"?: (string | null);
/**
 * Whether trusted system operations may install from private URL manifests.
 * 可信 system 操作是否允许从私有 URL manifest 安装。
 */
"enable_private_url_skill_install"?: boolean;
/**
 * Optional GitHub API base URL override used to resolve release metadata.
 * 可选的 GitHub API 基址覆盖，用于解析 release 元数据。
 */
"github_api_base_url"?: (string | null);
/**
 * Optional GitHub site base URL override used to rewrite browser download URLs.
 * 可选的 GitHub 站点基址覆盖，用于重写浏览器下载地址。
 */
"github_base_url"?: (string | null);
/**
 * Host-managed root directory used only to probe host-provided FFI/native dependencies.
 * 仅用于探测宿主提供 FFI/原生依赖的宿主管理根目录。
 */
"host_provided_ffi_root"?: (string | null);
/**
 * Host-managed root directory used only to probe host-provided Lua package dependencies.
 * 仅用于探测宿主提供 Lua 包依赖的宿主管理根目录。
 */
"host_provided_lua_root"?: (string | null);
/**
 * Host-managed root directory used only to probe host-provided tool dependencies.
 * 仅用于探测宿主提供工具依赖的宿主管理根目录。
 */
"host_provided_tool_root"?: (string | null);
/**
 * Host-forced skill identifiers that must be skipped before dependency or database setup.
 * 宿主强制跳过的技能标识符列表，会在依赖或数据库初始化前生效。
 */
"ignored_skill_ids"?: Array<string>;
/**
 * LanceDB callback transport mode selected by the host when provider mode is `host_callback`.
 * 当 provider 模式为 `host_callback` 时，宿主为 LanceDB 选择的回调传输模式。
 */
"lancedb_callback_mode"?: InputLuaRuntimeDatabaseCallbackMode;
/**
 * Explicit LanceDB dynamic-library path owned by the host.
 * 由宿主显式提供的 LanceDB 动态库路径。
 */
"lancedb_library_path"?: (string | null);
/**
 * LanceDB database provider mode selected by the host.
 * 宿主为 LanceDB 数据库选择的 provider 模式。
 */
"lancedb_provider_mode"?: InputLuaRuntimeDatabaseProviderMode;
/**
 * Optional lua_packages root used to build `package.path` and `package.cpath`.
 * 用于拼接 `package.path` 与 `package.cpath` 的可选 lua_packages 根目录。
 */
"lua_packages_dir"?: (string | null);
/**
 * Host-selected managed Python/Node worker and persistent-session resource policy.
 * 宿主选择的受管 Python/Node Worker 与持久会话资源策略。
 */
"managed_runtime_config"?: InputLuaRuntimeManagedRuntimeConfig;
/**
 * Optional host-configured read-only root containing managed Python and Node distributions.
 * 可选的宿主配置只读根目录，包含受管 Python 与 Node 发行包。
 */
"managed_runtime_distribution_root"?: (string | null);
/**
 * Optional host-configured writable root containing reusable managed environments.
 * 可选的宿主配置可写根目录，包含可复用受管环境。
 */
"managed_runtime_environment_root"?: (string | null);
/**
 * Optional official LuaSkills Hub base URL used by managed Hub installs.
 * 受管 Hub 安装使用的可选官方 LuaSkills Hub 基址。
 */
"official_skill_hub_base_url"?: (string | null);
/**
 * Host-controlled URL prefixes allowed for private skill manifests.
 * 宿主管控的私有技能 manifest 允许 URL 前缀。
 */
"private_skill_source_allowlist"?: Array<string>;
/**
 * Host-reserved public entry names that LuaSkills canonical name generation must never occupy directly.
 * 宿主保留的公开入口名称集合，LuaSkills 在生成 canonical 名称时必须直接避开这些名称。
 */
"reserved_entry_names": Array<string>;
/**
 * Optional host-managed resources directory exposed to Lua as `vulcan.runtime.resources_dir`.
 * 以 `vulcan.runtime.resources_dir` 形式暴露给 Lua 的可选宿主管理资源目录。
 */
"resources_dir"?: (string | null);
/**
 * Optional dedicated pool configuration for isolated `vulcan.runtime.lua.exec` VMs.
 * 供隔离 `vulcan.runtime.lua.exec` 虚拟机使用的可选独立池配置。
 */
"runlua_pool_config"?: (InputLuaRuntimeRunLuaPoolConfig | null);
/**
 * Optional canonical LuaSkills runtime root used to derive the fixed runtime layout.
 * 用于推导固定运行时布局的可选规范 LuaSkills 运行时根目录。
 */
"runtime_root"?: (string | null);
/**
 * Optional cross-process configuration lock timeout in milliseconds.
 * 可选的配置跨进程锁超时毫秒数。
 */
"skill_config_lock_timeout_ms"?: (EmbeddedInteger | null);
/**
 * Explicit user-level root containing normal and system skill configuration stores.
 * 包含普通技能与系统技能配置存储的显式用户级根目录。
 */
"skill_config_root"?: (string | null);
/**
 * Optional configuration file watcher debounce interval in milliseconds.
 * 可选的配置文件监听防抖毫秒数。
 */
"skill_config_watch_debounce_ms"?: (EmbeddedInteger | null);
/**
 * Shared controller client options used when one database backend selects `space_controller`.
 * 当数据库后端选择 `space_controller` 时所使用的共享控制器客户端选项。
 */
"space_controller"?: InputLuaRuntimeSpaceControllerOptions;
/**
 * SQLite callback transport mode selected by the host when provider mode is `host_callback`.
 * 当 provider 模式为 `host_callback` 时，宿主为 SQLite 选择的回调传输模式。
 */
"sqlite_callback_mode"?: InputLuaRuntimeDatabaseCallbackMode;
/**
 * Explicit SQLite dynamic-library path owned by the host.
 * 由宿主显式提供的 SQLite 动态库路径。
 */
"sqlite_library_path"?: (string | null);
/**
 * SQLite database provider mode selected by the host.
 * 宿主为 SQLite 数据库选择的 provider 模式。
 */
"sqlite_provider_mode"?: InputLuaRuntimeDatabaseProviderMode;
/**
 * Fixed sibling directory name used under one skill-root parent to store skill state.
 * 在单个技能根父目录下存放技能状态时使用的固定兄弟目录名称。
 */
"state_dir_name"?: string;
/**
 * Optional fixed host-owned system Lua library directory used by `system_lua_lib` leases.
 * 供 `system_lua_lib` 租约使用的可选固定宿主系统 Lua 库目录。
 */
"system_lua_lib_dir"?: (string | null);
/**
 * Host-managed temporary directory used by luaexec spill files and similar transient artifacts.
 * 宿主管理的临时目录，供 luaexec 请求文件等短生命周期产物使用。
 */
"temp_dir"?: (string | null);
} & Record<string, EmbeddedJsonValue>);

/**
 * Host-selected resource policy for managed Python and Node workers and persistent sessions.
 * 宿主为受管 Python 与 Node Worker 及持久会话选择的资源策略。
 */
export type InputLuaRuntimeManagedRuntimeConfig = ({
/**
 * Default positive invoke timeout in milliseconds; absent means unlimited.
 * 默认正数 invoke 超时毫秒数；缺失表示无限制。
 */
"invoke_default_timeout_ms"?: (EmbeddedInteger | null);
/**
 * Default retained byte limit for each persistent-session stdout or stderr stream.
 * 每个持久会话 stdout 或 stderr 流默认保留的字节上限。
 */
"persistent_session_default_buffer_limit_bytes_per_stream": EmbeddedInteger;
/**
 * Maximum launching or live persistent sessions retained by one engine.
 * 单个引擎允许保留的启动中或活动持久会话最大数量。
 */
"persistent_session_limit_per_engine": EmbeddedInteger;
/**
 * Idle seconds after which an unused worker may be retired.
 * 未使用 Worker 可被回收前的空闲秒数。
 */
"worker_idle_ttl_secs": EmbeddedInteger;
/**
 * Maximum live workers for one exact environment and package-owner pool key.
 * 单个精确环境与包所有者池键允许的最大活动 Worker 数量。
 */
"worker_pool_max_size_per_environment": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Host-provided pool configuration for isolated runlua VMs.
 * 宿主提供的隔离 runlua 虚拟机池配置。
 */
export type InputLuaRuntimeRunLuaPoolConfig = ({
/**
 * Idle TTL in seconds before one excess isolated runlua VM may be retired.
 * 多余隔离 runlua 虚拟机在空闲多少秒后允许回收。
 */
"idle_ttl_secs": EmbeddedInteger;
/**
 * Maximum number of isolated runlua VMs allowed in the pool.
 * 隔离 runlua 虚拟机池允许存在的最大数量。
 */
"max_size": EmbeddedInteger;
/**
 * Minimum number of isolated runlua VMs kept warm.
 * 隔离 runlua 虚拟机需要常驻保温的最小数量。
 */
"min_size": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Host-provided controller client options used when one database backend chooses `space_controller`.
 * 当数据库后端选择 `space_controller` 时使用的宿主侧控制器客户端选项。
 */
export type InputLuaRuntimeSpaceControllerOptions = ({
/**
 * Whether the runtime may auto-spawn the controller when the endpoint is unavailable.
 * 当控制器端点不可用时，运行时是否允许自动唤起控制器。
 */
"auto_spawn": boolean;
/**
 * Transport connect timeout in seconds used by the controller client proxy.
 * 控制器客户端代理使用的传输连接超时秒数。
 */
"connect_timeout_secs": EmbeddedInteger;
/**
 * Default lease TTL in seconds passed to one auto-spawned controller.
 * 传递给自动唤起控制器的默认租约 TTL 秒数。
 */
"default_lease_ttl_secs": EmbeddedInteger;
/**
 * Optional explicit controller endpoint; when omitted the shared default endpoint is used.
 * 可选的显式控制器端点；缺失时使用共享默认端点。
 */
"endpoint"?: (string | null);
/**
 * Optional local executable path copied and managed by the host.
 * 由宿主复制并管理的可选本地可执行文件路径。
 */
"executable_path"?: (string | null);
/**
 * Idle timeout in seconds passed to one auto-spawned controller.
 * 传递给自动唤起控制器的空闲超时秒数。
 */
"idle_timeout_secs": EmbeddedInteger;
/**
 * Lease renew interval in seconds used by the background controller client task.
 * 后台控制器客户端任务使用的租约续约间隔秒数。
 */
"lease_renew_interval_secs": EmbeddedInteger;
/**
 * Minimum uptime in seconds passed to one auto-spawned controller.
 * 传递给自动唤起控制器的最小存活秒数。
 */
"minimum_uptime_secs": EmbeddedInteger;
/**
 * Process mode used when auto-spawning one controller process.
 * 自动唤起控制器进程时使用的进程模式。
 */
"process_mode": InputLuaRuntimeSpaceControllerProcessMode;
/**
 * Startup retry interval in milliseconds used while polling one spawned controller.
 * 轮询已唤起控制器时使用的启动重试间隔毫秒数。
 */
"startup_retry_interval_ms": EmbeddedInteger;
/**
 * Startup timeout in seconds used while waiting for one spawned controller to become ready.
 * 等待已唤起控制器就绪时使用的启动超时秒数。
 */
"startup_timeout_secs": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Process mode used when the runtime auto-spawns one local space controller process.
 * 运行时自动拉起本地空间控制器进程时使用的进程模式。
 */
export type InputLuaRuntimeSpaceControllerProcessMode = ("service" | "managed");

/**
 * Pool sizing configuration for Lua virtual machines.
 * Lua 虚拟机池的容量配置。
 */
export type InputLuaVmPoolConfig = ({
/**
 * Idle TTL in seconds before an excess VM can be retired.
 * 多余虚拟机在空闲多少秒后允许回收。
 */
"idle_ttl_secs": EmbeddedInteger;
/**
 * Maximum number of VMs allowed in the pool.
 * 池内允许存在的最大虚拟机数量。
 */
"max_size": EmbeddedInteger;
/**
 * Minimum number of VMs that should stay warm.
 * 需要常驻保温的最小虚拟机数量。
 */
"min_size": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Immutable source and trusted path declaration supplied during module activation.
 * 模块激活时提供的不可变源码与可信路径声明。
 */
export type InputModuleDefinition = ({
/**
 * Logical working directory; absent selects the existing package-root rule.
 * 逻辑工作目录；省略时使用既有包根目录规则。
 */
"cwd"?: (string | null);
/**
 * Package-relative dependency manifest, validated by the existing package loader.
 * 由既有包加载器校验的包相对依赖清单。
 */
"dependencies_file": string;
/**
 * Exact public exports and value contracts validated before invocation.
 * 调用前校验的精确公开导出及值契约。
 */
"exports": Array<InputModuleExport>;
/**
 * Host-assigned immutable code and dependency generation.
 * 宿主分配的不可变代码与依赖代次。
 */
"generation": string;
/**
 * Trusted mount metadata; must be a JSON object.
 * 可信挂载元数据，必须为 JSON 对象。
 */
"mounts": EmbeddedJsonValue;
/**
 * Absolute plugin root inside the configured System trust root.
 * 位于已配置 System 信任根内的绝对插件根目录。
 */
"package_root": string;
/**
 * Host-assigned stable plugin identity.
 * 宿主分配的稳定插件身份。
 */
"plugin_id": string;
/**
 * Host-authenticated security partition used for instance matching.
 * 用于实例匹配且由宿主认证的安全分区。
 */
"security_partition": string;
/**
 * Source evaluated once; it must return a table of declared functions.
 * 仅求值一次的源码；必须返回已声明函数的表。
 */
"source": string;
/**
 * Explicitly authorized workspace root, absent for package-only execution.
 * 显式授权的工作区根目录；仅在包内执行时省略。
 */
"workspace_root"?: (string | null);
});

/**
 * One named export with explicit input and output schemas.
 * 具有显式输入及输出 Schema 的单个具名导出。
 */
export type InputModuleExport = ({
/**
 * Offline Draft 2020-12 schema for structured invocation arguments.
 * 结构化调用参数的离线 Draft 2020-12 Schema。
 */
"input_schema": EmbeddedJsonValue;
/**
 * Exact Lua table key captured when the module is loaded.
 * 模块加载时捕获的精确 Lua 表键。
 */
"name": string;
/**
 * Offline Draft 2020-12 schema for structured return values.
 * 结构化返回值的离线 Draft 2020-12 Schema。
 */
"output_schema": EmbeddedJsonValue;
});

/**
 * Immutable capacity policy for one host-assigned plugin execution group.
 * 单个宿主分配的插件执行分组的不可变容量策略。
 */
export type InputPluginPoolConfig = ({
/**
 * Requested execution backend, validated before activation.
 * 激活前校验的所请求执行后端。
 */
"backend": InputExecutionBackend;
/**
 * Idle retirement threshold; absent explicitly disables idle retirement.
 * 空闲退役阈值；省略明确表示关闭空闲退役。
 */
"idle_ttl_ms"?: (EmbeddedInteger | null);
/**
 * Shared or dedicated ownership of resident capacity.
 * 常驻容量的公共或专用归属。
 */
"kind": InputPoolKind;
/**
 * Maximum pending calls in this group.
 * 当前分组等待调用的数量上限。
 */
"max_queued_calls": EmbeddedInteger;
/**
 * Maximum resident instances in this exact immutable execution domain.
 * 此精确不可变执行域的最大常驻实例数。
 */
"max_resident_vms": EmbeddedInteger;
/**
 * Maximum simultaneously executing calls in this group.
 * 当前分组同时执行的调用数上限。
 */
"max_running_calls": EmbeddedInteger;
/**
 * Maximum successful uses before retirement; absent disables this limit.
 * 退役前成功使用次数上限；省略表示关闭此上限。
 */
"max_uses"?: (EmbeddedInteger | null);
/**
 * Non-lendable reservation; only dedicated groups may reserve capacity.
 * 不可出借的预留；仅专用分组可以预留容量。
 */
"min_resident_vms": EmbeddedInteger;
/**
 * Module state lifetime; legacy stateless calls select single-call mode.
 * 模块状态寿命；旧无状态调用选择单次模式。
 */
"reuse": InputInstanceReuse;
/**
 * Whether all calls in this group require FIFO serialization.
 * 当前分组的全部调用是否要求先进先出的串行执行。
 */
"serial": boolean;
});

/**
 * Capacity ownership, separate from instance reuse and ordering requirements.
 * 容量归属，与实例复用及顺序要求相互独立。
 */
export type InputPoolKind = ("shared" | "dedicated");

/**
 * Generic host-side client identity information passed into the LuaSkills runtime.
 * 传入 LuaSkills 运行时的通用宿主客户端身份信息。
 */
export type InputRuntimeClientInfo = ({
/**
 * Stable host-defined client kind, such as `mcp`, `ide`, or `desktop`.
 * 宿主定义的稳定客户端类型，例如 `mcp`、`ide` 或 `desktop`。
 */
"kind"?: (string | null);
/**
 * Human-readable client name reported by the host.
 * 由宿主上报的人类可读客户端名称。
 */
"name"?: (string | null);
/**
 * Optional client version string.
 * 可选的客户端版本字符串。
 */
"version"?: (string | null);
} & Record<string, EmbeddedJsonValue>);

/**
 * Typed commands for one already initialized runtime; every identity stays bound to that runtime.
 * 一个已初始化运行时的类型化命令；每个身份始终绑定该运行时。
 */
export type InputRuntimeCommand = (({
/**
 * Explicit aggregate plugin budgets.
 * 显式插件聚合预算。
 */
"config": InputEmbeddedPluginConfig;
/**
 * Exact host-assigned plugin identity.
 * 精确宿主分配的插件身份。
 */
"plugin_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "plugin_register";
}) | ({
/**
 * Exact host-assigned plugin identity.
 * 精确宿主分配的插件身份。
 */
"plugin_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "plugin_status";
}) | ({
/**
 * Exact host-assigned plugin identity.
 * 精确宿主分配的插件身份。
 */
"plugin_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "plugin_close";
}) | ({
/**
 * Exact host-assigned plugin identity.
 * 精确宿主分配的插件身份。
 */
"plugin_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "plugin_forget";
}) | ({
/**
 * Immutable package and module declaration.
 * 不可变包与模块声明。
 */
"definition": InputModuleDefinition;
/**
 * Immutable host initialization and configuration revision.
 * 不可变宿主初始化及配置修订。
 */
"execution_revision": string;
/**
 * Explicit host grants for this binding or discovery request.
 * 此绑定或发现请求的显式宿主授权。
 */
"permissions": Array<string>;
/**
 * Explicit immutable VM pool policy.
 * 显式不可变 VM 池策略。
 */
"policy": InputPluginPoolConfig;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "pool_register";
}) | ({
/**
 * Exact immutable pool identity.
 * 精确不可变池身份。
 */
"pool_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "pool_status";
}) | ({
/**
 * Exact immutable pool identity.
 * 精确不可变池身份。
 */
"pool_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "pool_close";
}) | ({
/**
 * Exact immutable pool identity.
 * 精确不可变池身份。
 */
"pool_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "pool_forget";
}) | ({
/**
 * Exact live permission to revoke.
 * 需要撤销的精确实时权限。
 */
"permission": string;
/**
 * Exact immutable pool identity.
 * 精确不可变池身份。
 */
"pool_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "pool_revoke_permission";
}) | ({
/**
 * Typed ordinary call bound to one exact pool.
 * 绑定一个精确池的类型化普通调用。
 */
"call": InputEmbeddedCall;
/**
 * Original end-to-end execution budget in milliseconds.
 * 原始端到端执行预算毫秒数。
 */
"timeout_ms": EmbeddedInteger;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "call_submit";
}) | ({
/**
 * Exact immutable pool identity.
 * 精确不可变池身份。
 */
"pool_id": string;
/**
 * Original end-to-end execution budget in milliseconds.
 * 原始端到端执行预算毫秒数。
 */
"timeout_ms": EmbeddedInteger;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "session_open";
}) | ({
/**
 * Structured application arguments.
 * 结构化应用参数。
 */
"arguments": EmbeddedJsonValue;
/**
 * Trusted host invocation context.
 * 可信宿主调用上下文。
 */
"context": InputLuaInvocationContext;
/**
 * Declared module export name.
 * 已声明模块导出名称。
 */
"export": string;
/**
 * Exact fixed-instance session identity.
 * 精确固定实例会话身份。
 */
"session_id": string;
/**
 * Original end-to-end execution budget in milliseconds.
 * 原始端到端执行预算毫秒数。
 */
"timeout_ms": EmbeddedInteger;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "session_submit";
}) | ({
/**
 * Exact fixed-instance session identity.
 * 精确固定实例会话身份。
 */
"session_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "session_status";
}) | ({
/**
 * Exact fixed-instance session identity.
 * 精确固定实例会话身份。
 */
"session_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "session_close";
}) | ({
/**
 * Exact fixed-instance session identity.
 * 精确固定实例会话身份。
 */
"session_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "session_forget";
}) | ({
/**
 * Exact retained operation identity.
 * 精确保留操作身份。
 */
"operation_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "operation_status";
}) | ({
/**
 * Exact retained operation identity.
 * 精确保留操作身份。
 */
"operation_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "operation_wait";
/**
 * Finite observer wait in milliseconds, independent of execution cancellation.
 * 有限观察者等待毫秒数，独立于执行取消。
 */
"wait_ms": EmbeddedInteger;
}) | ({
/**
 * Exact retained operation identity.
 * 精确保留操作身份。
 */
"operation_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "operation_cancel";
}) | ({
/**
 * Exact retained operation identity.
 * 精确保留操作身份。
 */
"operation_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "operation_forget";
}) | ({
/**
 * Batch of explicit queued capability declarations.
 * 显式队列能力声明批次。
 */
"descriptors": Array<InputCapabilityDescriptor>;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "capabilities_register";
}) | ({
/**
 * Explicit host grants for this binding or discovery request.
 * 此绑定或发现请求的显式宿主授权。
 */
"permissions": Array<string>;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "capabilities_list";
}) | ({
/**
 * Exact capability registration identity.
 * 精确能力注册身份。
 */
"registration_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "capability_status";
}) | ({
/**
 * Exact capability registration identity.
 * 精确能力注册身份。
 */
"registration_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "capability_unregister";
}) | ({
/**
 * Exact capability registration identity.
 * 精确能力注册身份。
 */
"registration_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "capability_forget";
}) | ({
/**
 * Maximum host requests in this one bounded batch.
 * 此单个有界批次的宿主请求数量上限。
 */
"limit": EmbeddedInteger;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "host_requests_take";
}) | ({
/**
 * Exact host request identity to query or acknowledge.
 * 用于查询或确认的精确宿主请求身份。
 */
"request_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "host_request_status";
}) | ({
/**
 * Actual host result and effect evidence, including late completion.
 * 实际宿主结果与副作用证据，包含迟到完成。
 */
"outcome": InputHostCompletion;
/**
 * Exact host request identity to query or acknowledge.
 * 用于查询或确认的精确宿主请求身份。
 */
"request_id": string;
/**
 * Generated wire shape for type.
 * type 的生成线形状。
 */
"type": "host_request_complete";
}));

/**
 * Generic request-scoped context injected by the host into one runtime invocation.
 * 宿主在单次运行时调用中注入的通用请求级上下文。
 */
export type InputRuntimeRequestContext = ({
/**
 * Optional host-provided raw client capabilities object.
 * 可选的宿主原始客户端能力对象。
 */
"client_capabilities"?: EmbeddedJsonValue;
/**
 * Optional host-side client metadata.
 * 可选的宿主客户端元数据。
 */
"client_info"?: (InputRuntimeClientInfo | null);
/**
 * Optional host-defined client name for audit and cost attribution.
 * 可选的宿主客户端名称，用于审计和成本归因。
 */
"client_name"?: (string | null);
/**
 * Optional host-defined request identifier for audit and cost attribution.
 * 可选的宿主请求标识符，用于审计和成本归因。
 */
"request_id"?: (string | null);
/**
 * Optional host-defined session identifier.
 * 可选的宿主会话标识。
 */
"session_id"?: (string | null);
/**
 * Optional host-defined transport name for the current request.
 * 当前请求的可选宿主传输层名称。
 */
"transport_name"?: (string | null);
} & Record<string, EmbeddedJsonValue>);

/**
 * Runtime configuration for the shared tool cache, controlling capacity and expiration behavior.
 * 共享工具缓存的运行时配置，控制容量与过期策略。
 */
export type InputToolCacheConfig = ({
/**
 * Default TTL in seconds used when callers omit a TTL.
 * 默认 TTL（秒），调用方未传 TTL 时使用。
 */
"default_ttl_secs": EmbeddedInteger;
/**
 * Maximum number of entries; oldest entries are evicted when the cache exceeds this size.
 * 缓存最大条目数，超出后会按创建顺序淘汰最旧条目。
 */
"max_entries": EmbeddedInteger;
/**
 * Maximum TTL in seconds; requested TTL values are clamped to this ceiling.
 * 最大 TTL（秒），请求 TTL 会被限制在该范围内。
 */
"max_ttl_secs": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Strict versioned request; unknown fields and commands are explicit protocol errors.
 * 严格版本化请求；未知字段与命令是明确协议错误。
 */
export type InputRequest = ({
/**
 * One typed operation; no legacy envelope aliases are inferred.
 * 一个类型化操作；不推断旧信封别名。
 */
"command": InputCommand;
/**
 * Explicit wire version, checked before dispatch.
 * 分发前检查的显式线协议版本。
 */
"protocol_version": number;
});

/**
 * Host-authenticated caller data copied outside plugin-controlled arguments.
 * 在插件可控参数之外复制的宿主认证调用方数据。
 */
export type OutputCapabilityCaller = ({
/**
 * Immutable execution and initialization-configuration revision.
 * 不可变执行与初始化配置修订。
 */
"execution_revision": string;
/**
 * Exact operation whose original budget applies.
 * 适用原始预算的精确操作。
 */
"operation_id": string;
/**
 * Immutable package and dependency generation.
 * 不可变包与依赖代次。
 */
"package_generation": string;
/**
 * Exact activated plugin identity.
 * 精确激活的插件身份。
 */
"plugin_id": string;
/**
 * Runtime namespace that owns the registration and operation.
 * 拥有注册及操作的运行时命名空间。
 */
"runtime_id": string;
/**
 * Trusted user/workspace partition, never copied from a Lua argument.
 * 可信用户与工作区分区，绝不从 Lua 参数复制。
 */
"security_partition": string;
/**
 * Optional fixed session required by session-scoped capabilities.
 * 会话作用域能力要求的可选固定会话。
 */
"session_id": (string | null);
/**
 * Explicit authorized workspace; absent means package-only context.
 * 显式授权工作区；省略表示仅包内上下文。
 */
"workspace_root": (string | null);
});

/**
 * Immutable capability declaration shared by Rust, generated contracts and SDKs.
 * Rust、生成契约与 SDK 共享的不可变能力声明。
 */
export type OutputCapabilityDescriptor = ({
/**
 * English description of the host capability for tool consumers.
 * 面向工具消费者的宿主能力英文描述。
 */
"description": string;
/**
 * Declared mutation category.
 * 声明的变更类别。
 */
"effects": OutputCapabilityEffects;
/**
 * Explicit native or queued dispatch protocol.
 * 显式原生或队列分发协议。
 */
"execution": OutputCapabilityExecution;
/**
 * Explicit host deduplication contract.
 * 显式宿主去重契约。
 */
"idempotency": OutputCapabilityIdempotency;
/**
 * Offline input value contract.
 * 离线输入值契约。
 */
"input_schema": EmbeddedJsonValue;
/**
 * Per-capability budget capped by the original operation deadline.
 * 受原始操作截止时间约束的单能力预算。
 */
"max_call_ms": EmbeddedInteger;
/**
 * Maximum in-flight handlers, including cancelled handlers that have not stopped.
 * 在途处理器上限，包含已取消但尚未停止的处理器。
 */
"max_concurrent": EmbeddedInteger;
/**
 * Maximum serialized input bytes within the parent value limit.
 * 父级值上限内的最大序列化输入字节数。
 */
"max_input_bytes": EmbeddedInteger;
/**
 * Maximum serialized output bytes within the parent value limit.
 * 父级值上限内的最大序列化输出字节数。
 */
"max_output_bytes": EmbeddedInteger;
/**
 * Exact namespaced name; discovery exposes only authorized declarations.
 * 精确命名空间名称；发现操作仅暴露已授权声明。
 */
"name": string;
/**
 * Offline output value contract.
 * 离线输出值契约。
 */
"output_schema": EmbeddedJsonValue;
/**
 * Every listed grant must still exist at each admission boundary.
 * 每个入场边界仍必须拥有列出的全部授权。
 */
"permissions": Array<string>;
/**
 * Required trusted invocation scope.
 * 必需的可信调用作用域。
 */
"scope": OutputCapabilityScope;
/**
 * Semantic interface version, independent from the core library version.
 * 语义接口版本，独立于核心库版本。
 */
"version": string;
});

/**
 * Declared effect category; it does not make external mutations transactional.
 * 声明的副作用类别；它不会使外部变更自动具有事务性。
 */
export type OutputCapabilityEffects = ("read_only" | "mutating");

/**
 * Host execution transport, explicitly selected before a capability is published.
 * 宿主执行传输，在能力发布前显式选择。
 */
export type OutputCapabilityExecution = ("native" | "queued");

/**
 * Explicit side-effect deduplication support, never inferred from an operation identifier.
 * 显式副作用去重支持，绝不从操作标识推断。
 */
export type OutputCapabilityIdempotency = ("none" | "host_request");

/**
 * Observable lifetime of an exact registration, including unregistration still draining calls.
 * 精确注册的可观察生命周期，包含注销后仍在排空的调用。
 */
export type OutputCapabilityRegistrationStatus = ({
/**
 * Whether new calls may enter this specific registration.
 * 新调用是否可以进入此特定注册。
 */
"accepting": boolean;
/**
 * True only after admission closed and all native callback references were released.
 * 仅在入场关闭且全部原生回调引用释放后为真。
 */
"drained": boolean;
/**
 * Actually executing or dispatched handlers, including pending cancellation.
 * 实际执行或已分发的处理器，包含等待取消完成的处理器。
 */
"in_flight": EmbeddedInteger;
/**
 * Exact declared capability name.
 * 精确声明的能力名称。
 */
"name": string;
/**
 * Opaque identity, never a lossy language number.
 * 不透明身份，绝不使用有精度损失的语言数值。
 */
"registration_id": string;
});

/**
 * Scope required from the trusted caller, independent from Lua business arguments.
 * 可信调用方必须具备的作用域，独立于 Lua 业务参数。
 */
export type OutputCapabilityScope = ("invocation" | "session");

/**
 * Host-reported effect outcome, independent from execution success or cancellation.
 * 宿主报告的副作用结果，独立于执行成功或取消。
 */
export type OutputEffectState = ("not_started" | "not_applicable" | "committed" | "rolled_back" | "unknown");

/**
 * Selected package and compiler input identities; binary authentication remains the release artifact's job.
 * 选定包及编译器输入身份；二进制认证仍由发布产物负责。
 */
export type OutputEmbeddedBuildIdentity = ({
/**
 * Sorted Cargo feature environment suffixes; they are not reverse-mapped into guessed feature names.
 * 排序后 Cargo 功能环境后缀；不反向映射为猜测功能名。
 */
"cargo_features": Array<string>;
/**
 * Exact bundled embedded contract identity, independently checked by SDKs.
 * 精确包内嵌入式契约身份，由 SDK 独立检查。
 */
"contract_sha256": string;
/**
 * Cargo's debug-information setting, independent of optimization.
 * Cargo 调试信息设置，独立于优化。
 */
"debug_info": string;
/**
 * SHA-256 of the exact machine-readable selected-input report emitted by build.rs.
 * build.rs 输出的精确机器可读选定输入报告的 SHA-256。
 */
"inputs_sha256": string;
/**
 * Actual Cargo optimization setting, not an inferred profile label.
 * 实际 Cargo 优化设置，不推断配置名称。
 */
"opt_level": string;
/**
 * Bundled package lockfile identity; a consuming Rust workspace may resolve a different dependency graph.
 * 包内锁文件身份；消费它的 Rust 工作区可能解析出不同依赖图。
 */
"package_lock_sha256": string;
/**
 * Cargo's target pointer width, preserved as its exact textual value.
 * Cargo 目标指针位宽，保留其精确文本值。
 */
"pointer_width": string;
/**
 * The selected rustc executable's verbose version output.
 * 所选 rustc 可执行文件的详细版本输出。
 */
"rustc": string;
/**
 * SHA-256 of Cargo's exact encoded additional compiler flags.
 * Cargo 精确编码额外编译参数的 SHA-256。
 */
"rustflags_sha256": string;
/**
 * SHA-256 of sorted package-relative input paths and their exact content hashes.
 * 排序后包相对输入路径及其精确内容摘要的 SHA-256。
 */
"source_sha256": string;
/**
 * Cargo's target triple for this build.
 * 此构建的 Cargo 目标三元组。
 */
"target": string;
/**
 * Cargo's target architecture identity.
 * Cargo 目标架构身份。
 */
"target_arch": string;
/**
 * Cargo's target operating-system identity.
 * Cargo 目标操作系统身份。
 */
"target_os": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Structured error; `code` is stable and `message` is an English diagnostic.
 * 结构化错误；`code` 稳定，`message` 为英文诊断信息。
 */
export type OutputEmbeddedError = ({
/**
 * Stable classification consumed by SDKs instead of parsing text.
 * 供 SDK 使用的稳定分类，避免解析文案。
 */
"code": OutputEmbeddedErrorCode;
/**
 * Human-readable detail without credentials or plugin input dumps.
 * 不含凭据或插件输入转储的可读详情。
 */
"message": string;
});

/**
 * Stable machine-readable failures shared by Rust and the versioned FFI protocol.
 * Rust 与版本化 FFI 协议共享的稳定机器可读错误。
 */
export type OutputEmbeddedErrorCode = ("invalid_argument" | "not_found" | "stale_generation" | "capacity_exceeded" | "busy" | "already_completed" | "closed" | "cancelled" | "deadline_exceeded" | "permission_denied" | "unsupported" | "execution_failed" | "cleanup_failed" | "internal");

/**
 * Immutable host-approved aggregate budgets across every generation and execution domain of one plugin.
 * 一个插件的全部代次与执行域共享的不可变宿主批准聚合预算。
 */
export type OutputEmbeddedPluginConfig = ({
/**
 * Maximum retained operations, including completed results not explicitly forgotten.
 * 保留操作的数量上限，包含尚未显式遗忘的已完成结果。
 */
"max_operations": EmbeddedInteger;
/**
 * Maximum exact serialized queued request bytes across this plugin.
 * 此插件全部排队请求精确序列化字节数上限。
 */
"max_queued_bytes": EmbeddedInteger;
/**
 * Maximum accepted queued calls across all domains and sessions.
 * 全部域和会话已接纳排队调用的合计上限。
 */
"max_queued_calls": EmbeddedInteger;
/**
 * Maximum retained pool identities, including closed generations awaiting explicit removal.
 * 保留池身份的数量上限，包含等待显式移除的已关闭代次。
 */
"max_registered_pools": EmbeddedInteger;
/**
 * Maximum actual resident VMs plus other domains' unused dedicated reservations.
 * 实际常驻 VM 与其他域未使用专用预留的合计上限。
 */
"max_resident_vms": EmbeddedInteger;
/**
 * Maximum dispatched operations, retained through initialization, host waiting and cleanup.
 * 已分发操作上限，计费覆盖初始化、宿主等待及清理。
 */
"max_running_calls": EmbeddedInteger;
/**
 * Maximum retained sessions, including closed session records.
 * 保留会话的数量上限，包含已关闭会话记录。
 */
"max_sessions": EmbeddedInteger;
});

/**
 * Plugin-wide observation from exact immutable pool ownership, including draining generations.
 * 根据精确不可变池归属形成的插件级观测，包含正在排空的代次。
 */
export type OutputEmbeddedPluginSnapshot = ({
/**
 * Dispatched unfinished operations, including initialization and cleanup.
 * 已分发未完成操作，包含初始化与清理。
 */
"active_operations": EmbeddedInteger;
/**
 * Whether new pool and call admission is permanently closed.
 * 新池及新调用入场是否已永久关闭。
 */
"closing": boolean;
/**
 * Actual residents plus all unused dedicated domain guarantees.
 * 实际常驻实例与全部未使用专用域保证的合计。
 */
"committed_resident_vms": EmbeddedInteger;
/**
 * Immutable effective aggregate policy.
 * 不可变有效聚合策略。
 */
"config": OutputEmbeddedPluginConfig;
/**
 * Trusted host plugin identity used by module definitions and fair scheduling.
 * 模块定义与公平调度使用的可信宿主插件身份。
 */
"plugin_id": string;
/**
 * Exact serialized bytes still held by queued requests.
 * 排队请求仍持有的精确序列化字节数。
 */
"queued_bytes": EmbeddedInteger;
/**
 * Accepted queued calls across every domain and session.
 * 全部域和会话已接纳的排队调用。
 */
"queued_calls": EmbeddedInteger;
/**
 * Actual resident VM counters through confirmed destruction.
 * 持续记账到确认销毁的实际常驻 VM 计数。
 */
"resources": OutputPoolUsage;
/**
 * Retained operations, including results whose callers dropped their handles.
 * 保留操作，包含调用方已丢弃句柄的结果。
 */
"retained_operations": EmbeddedInteger;
/**
 * Retained pools, including closed metadata not explicitly forgotten.
 * 保留池，包含尚未显式遗忘的已关闭元数据。
 */
"retained_pools": EmbeddedInteger;
/**
 * Retained fixed sessions, including closed records.
 * 保留固定会话，包含已关闭记录。
 */
"retained_sessions": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Live scheduler observations; queue bytes exclude already-dispatched request values.
 * 实时调度观测；队列字节不包含已分发的请求值。
 */
export type OutputEmbeddedRuntimeUsage = ({
/**
 * Nonqueued unfinished operations, including rejected requests awaiting terminal publication.
 * 不在队列中的未完成操作，包含等待终态发布的已拒绝请求。
 */
"active_operations": EmbeddedInteger;
/**
 * Operations whose execution returned and whose cleanup remains owned.
 * 执行已返回但仍拥有清理的操作。
 */
"cleaning_operations": EmbeddedInteger;
/**
 * Whether new admission has permanently closed.
 * 新入场是否已永久关闭。
 */
"closing": boolean;
/**
 * Exact serialized queued request bytes.
 * 排队请求的精确序列化字节数。
 */
"queued_bytes": EmbeddedInteger;
/**
 * Requests waiting for actual resource admission.
 * 等待实际资源入场的请求。
 */
"queued_calls": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Observable pinned-session lifecycle; closing never implies that its VM is already destroyed.
 * 可观察的固定会话生命周期；正在关闭绝不表示其 VM 已销毁。
 */
export type OutputEmbeddedSessionPhase = ("opening" | "ready" | "running" | "closing" | "closed");

/**
 * Bounded retained session observation with immutable pool ownership.
 * 具有不可变池归属的有界保留会话观测。
 */
export type OutputEmbeddedSessionSnapshot = ({
/**
 * Current operation, including initialization and cleanup; absent while idle.
 * 当前操作，包含初始化与清理；空闲时省略。
 */
"active_operation": (string | null);
/**
 * First execution failure that made the session unusable.
 * 导致会话不可用的首次执行错误。
 */
"error": (OutputEmbeddedError | null);
/**
 * Current lifecycle observation.
 * 当前生命周期观测。
 */
"phase": OutputEmbeddedSessionPhase;
/**
 * Exact generation and security partition fixed at creation.
 * 创建时固定的精确代次与安全分区。
 */
"pool_id": string;
/**
 * Accepted calls waiting behind this session's current owner.
 * 此会话当前所有者之后等待的已接纳调用数。
 */
"queued_calls": EmbeddedInteger;
/**
 * Runtime-issued opaque identity, never reused after forgetting.
 * 运行时签发的不透明身份，遗忘后绝不复用。
 */
"session_id": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Single legal business-error discriminator, independent of native transport failures.
 * 独立于原生传输失败的唯一合法业务错误判别。
 */
export type OutputErrorStatus = ("error");

/**
 * Declared backend; unavailable variants are rejected instead of downgraded.
 * 声明的执行后端；不可用的取值直接拒绝，不降级。
 */
export type OutputExecutionBackend = ("in_process" | "worker_process");

/**
 * Actual handler lifecycle, separate from its reported business effect.
 * 真实处理器生命周期，独立于其报告的业务副作用。
 */
export type OutputHostEffectPhase = ("prepared" | "running" | "completed");

/**
 * Bounded evidence retained independently from values returned to Lua.
 * 独立于返回 Lua 的值保留的有界证据。
 */
export type OutputHostEffectRecord = ({
/**
 * Original host-bound caller identity, retained for reconciliation without consulting a newer plugin generation.
 * 原始宿主绑定调用身份；对账保留该身份，不查询较新的插件代次。
 */
"caller": OutputCapabilityCaller;
/**
 * Public capability name, excluding business arguments and credentials.
 * 公开能力名称，不包含业务参数与凭证。
 */
"capability_name": string;
/**
 * Interface version of the exact registration.
 * 精确注册的接口版本。
 */
"capability_version": string;
/**
 * Never-reused identity within the original operation.
 * 原始操作内绝不复用的身份。
 */
"effect_id": string;
/**
 * Trusted host evidence, independent from caller cancellation.
 * 可信宿主证据，独立于调用方取消。
 */
"effects": OutputEffectState;
/**
 * Actual handler ownership lifecycle.
 * 真实处理器所有权生命周期。
 */
"phase": OutputHostEffectPhase;
/**
 * Exact immutable registration identity.
 * 精确不可变注册身份。
 */
"registration_id": string;
/**
 * SDK request identity for queued execution.
 * 队列执行的 SDK 请求身份。
 */
"request_id": (string | null);
});

/**
 * SDK request copied from an admitted, authenticated invocation.
 * 从已入场、已认证调用复制的 SDK 请求。
 */
export type OutputHostRequest = ({
/**
 * Validated structured business arguments.
 * 已校验的结构化业务参数。
 */
"arguments": EmbeddedJsonValue;
/**
 * Trusted host identity, separate from business arguments.
 * 可信宿主身份，独立于业务参数。
 */
"caller": OutputCapabilityCaller;
/**
 * Original operation effect record, absent only for untracked low-level calls.
 * 原始操作副作用记录，仅未跟踪低层调用省略。
 */
"effect_id": (string | null);
/**
 * Declared capability name.
 * 声明的能力名称。
 */
"name": string;
/**
 * Exact registration, independent from later replacement by name.
 * 精确注册，独立于后续按名称替换。
 */
"registration_id": string;
/**
 * Advisory remaining duration; the core retains the original deadline.
 * 建议剩余时长；核心保留原始截止时间。
 */
"remaining_ms": EmbeddedInteger;
/**
 * Never-reused identity used for completion and host-side deduplication.
 * 用于完成与宿主侧去重、绝不复用的身份。
 */
"request_id": string;
/**
 * Declared semantic interface version.
 * 声明的语义接口版本。
 */
"version": string;
});

/**
 * Observable request phase; cancellation does not imply handler termination.
 * 可观察请求阶段；取消不代表处理器已经终止。
 */
export type OutputHostRequestPhase = ("queued" | "dispatched" | "completing" | "completed");

/**
 * Live request status for SDK cancellation and orderly runtime shutdown.
 * 用于 SDK 取消与运行时有序关闭的实时请求状态。
 */
export type OutputHostRequestStatus = ({
/**
 * Cooperative cancellation reason, preserved until actual completion.
 * 协作取消原因，保留到真实完成。
 */
"cancellation": (OutputEmbeddedError | null);
/**
 * Actual execution lifecycle.
 * 真实执行生命周期。
 */
"phase": OutputHostRequestPhase;
/**
 * Exact request identity.
 * 精确请求身份。
 */
"request_id": string;
});

/**
 * Initialization ownership is separate from the core's execution and closing state.
 * 初始化所有权独立于核心的执行及关闭状态。
 */
export type OutputInitializationPhase = ("reserved" | "initializing" | "ready" | "failed" | "faulted");

/**
 * Explicit operation origin; unbound low-level work is never inferred to belong to a current plugin.
 * 明确的操作来源；未绑定的低层工作绝不被推断归属于当前插件。
 */
export type OutputOperationContext = (({
/**
 * Generated wire shape for kind.
 * kind 的生成线形状。
 */
"kind": "unbound";
}) | ({
/**
 * Original trusted caller shared by initialization and this operation's host callbacks.
 * 初始化及此操作宿主回调共同使用的原始可信调用方。
 */
"caller": OutputCapabilityCaller;
/**
 * Exact capability membership snapshot frozen when the pool was registered.
 * 注册池时冻结的精确能力成员快照。
 */
"capability_revision": string;
/**
 * Requested declared export; absent only for a fixed-session opening operation.
 * 请求的已声明导出；仅固定会话开启操作省略。
 */
"export": (string | null);
/**
 * Generated wire shape for kind.
 * kind 的生成线形状。
 */
"kind": "module";
/**
 * Exact retained pool identity, not a lookup of the plugin's newest pool.
 * 精确保留池身份，不查询插件最新的池。
 */
"pool_id": string;
}));

/**
 * Execution phase; cancellation intent is reported separately from actual termination.
 * 执行阶段；取消意图与实际终止分开报告。
 */
export type OutputOperationPhase = ("queued" | "initializing" | "running" | "waiting_for_host" | "cleaning" | "succeeded" | "failed" | "cancelled");

/**
 * Actual operation admission acknowledgement; it does not imply execution completion.
 * 实际操作入场确认；不代表执行完成。
 */
export type OutputOperationReceipt = ({
/**
 * Retained queryable operation identity.
 * 保留且可查询的操作身份。
 */
"operation_id": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Bounded operation snapshot suitable for direct serialization to every SDK.
 * 适合直接序列化给各 SDK 的有界操作快照。
 */
export type OutputOperationSnapshot = ({
/**
 * Whether cooperative cancellation has been requested.
 * 是否已请求协作取消。
 */
"cancellation_requested": boolean;
/**
 * Admission-time module authority, or an explicit unbound low-level origin; never reconstructed from effects.
 * 入场时模块权威，或明确未绑定的低层来源；绝不从副作用重建。
 */
"context": OutputOperationContext;
/**
 * Explicit effect status; successful execution does not automatically imply commit.
 * 显式副作用状态；执行成功不自动表示提交。
 */
"effects": OutputEffectState;
/**
 * Structured terminal error; absent while execution is still in progress.
 * 结构化终态错误；执行仍在进行时省略。
 */
"error"?: (OutputEmbeddedError | null);
/**
 * Exact host callback evidence retained even after Lua failure, cancellation or output rejection.
 * 即使 Lua 失败、取消或输出被拒绝也保留的精确宿主回调证据。
 */
"host_effects": Array<OutputHostEffectRecord>;
/**
 * Opaque identifier, never a JavaScript floating-point integer.
 * 不透明标识符，绝不使用 JavaScript 浮点整数。
 */
"operation_id": string;
/**
 * Current execution phase, including still-running cancelled requests.
 * 当前执行阶段，包含已请求取消但仍在运行的请求。
 */
"phase": OutputOperationPhase;
/**
 * Successful value; absent before completion or on failure, distinct from JSON null.
 * 成功值；完成前或失败时省略，与 JSON 空值不同。
 */
"value"?: EmbeddedJsonValue;
});

/**
 * Actual pool registration acknowledgement shared by capacity preparation and publication.
 * 容量准备及发布共享的实际池注册确认。
 */
export type OutputPoolReceipt = ({
/**
 * Immutable core pool identity.
 * 不可变核心池身份。
 */
"pool_id": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Current counters for one governor or one execution group.
 * 单个治理器或执行分组的当前计数。
 */
export type OutputPoolUsage = ({
/**
 * Allocations that have not finished initialization.
 * 尚未完成初始化的分配。
 */
"creating": EmbeddedInteger;
/**
 * Initialized allocations that do not currently execute.
 * 已初始化且当前未执行的分配。
 */
"idle": EmbeddedInteger;
/**
 * All allocated slots, including creating and retiring instances.
 * 全部分配槽位，包含正在创建与退役的实例。
 */
"resident": EmbeddedInteger;
/**
 * Allocations retained until teardown has genuinely completed.
 * 保留到清理真正完成的分配。
 */
"retiring": EmbeddedInteger;
/**
 * Allocations holding a parent and group execution permit together.
 * 同时持有父级与分组执行许可的分配。
 */
"running": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Exact identities from one atomic host capability publication.
 * 单次原子宿主能力发布的精确身份。
 */
export type OutputRegistrationReceipt = ({
/**
 * Identities retain the descriptor batch's original order.
 * 身份保留描述符批次的原始顺序。
 */
"registration_ids": Array<string>;
} & Record<string, EmbeddedJsonValue>);

/**
 * Exact lifecycle identity returned before or after a runtime control mutation.
 * 在运行时控制变更前或后返回的精确生命周期身份。
 */
export type OutputRuntimeReceipt = ({
/**
 * Immutable transport-local runtime identity.
 * 不可变传输局部运行时身份。
 */
"runtime_id": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Queryable construction and core closure evidence; no runtime implementation state is inferred by SDKs.
 * 可查询构造与核心关闭证据；SDK 不推断运行时实现状态。
 */
export type OutputRuntimeSnapshot = ({
/**
 * True only after native core workers have exited, or no core was ever created.
 * 仅当原生核心工作线程已退出或从未创建核心时为真。
 */
"closed": boolean;
/**
 * Whether this slot has permanently closed admission.
 * 此槽是否已永久关闭入场。
 */
"closing": boolean;
/**
 * Actual runtime namespace, present only after successful construction.
 * 实际运行时命名空间，仅在成功构造后存在。
 */
"core_runtime_id": (string | null);
/**
 * Retained failure; a failed construction still owns its bounded registration until explicit release.
 * 保留失败；构造失败仍拥有其有界注册，直到显式释放。
 */
"error": (OutputEmbeddedError | null);
/**
 * Actual one-shot construction state.
 * 实际单次构造状态。
 */
"initialization": OutputInitializationPhase;
/**
 * Live resident and execution accounting directly from the core when available.
 * 可用时直接来自核心的实时常驻与执行计数。
 */
"resources": (OutputPoolUsage | null);
/**
 * Exact FFI slot identity used by every control command.
 * 每个控制命令使用的精确 FFI 槽身份。
 */
"runtime_id": string;
/**
 * Live scheduler observations directly from the core when available.
 * 可用时直接来自核心的实时调度观测。
 */
"usage": (OutputEmbeddedRuntimeUsage | null);
} & Record<string, EmbeddedJsonValue>);

/**
 * Fixed-session reservation and its independently queryable initialization operation.
 * 固定会话预留及其可独立查询的初始化操作。
 */
export type OutputSessionReceipt = ({
/**
 * Initialization operation whose actual outcome must be observed separately.
 * 必须单独观察实际结果的初始化操作。
 */
"operation_id": string;
/**
 * Immutable fixed-session identity.
 * 不可变固定会话身份。
 */
"session_id": string;
} & Record<string, EmbeddedJsonValue>);

/**
 * Single legal success discriminator, shared by live encoding and derived contracts.
 * 实际编码及派生契约共享的唯一合法成功判别。
 */
export type OutputSuccessStatus = ("ok");

/**
 * Validated native-sized transport configuration, copied once from the host declaration.
 * 从宿主声明一次性复制的已校验原生大小传输配置。
 */
export type OutputTransportConfig = ({
/**
 * Per-request byte limit.
 * 逐请求字节上限。
 */
"max_request_bytes": EmbeddedInteger;
/**
 * Per-response pre-dispatch reservation.
 * 逐响应分发前预留。
 */
"max_response_bytes": EmbeddedInteger;
/**
 * Maximum response owners, including pre-dispatch reservations.
 * 响应所有者数量上限，包含分发前预留。
 */
"max_result_buffers": EmbeddedInteger;
/**
 * Aggregate response allocation budget.
 * 聚合响应分配预算。
 */
"max_result_bytes": EmbeddedInteger;
/**
 * Maximum retained runtime identities.
 * 保留运行时身份数量上限。
 */
"max_runtimes": EmbeddedInteger;
} & Record<string, EmbeddedJsonValue>);

/**
 * Implemented transport description; every field comes from the running core's own authority.
 * 已实现传输描述；每个字段均来自运行核心自身权威。
 */
export type OutputTransportDescription = ({
/**
 * Version of the independent embedded ABI structures.
 * 独立嵌入式 ABI 结构版本。
 */
"abi_structure_version": number;
/**
 * Root commands implemented by the exhaustive dispatcher.
 * 穷尽分发器实现的根命令。
 */
"commands": Array<string>;
/**
 * Cargo package version of this exact library build.
 * 此精确动态库构建的 Cargo 包版本。
 */
"core_version": string;
/**
 * Actual validated transport limits supplied at construction.
 * 构造时提供的实际已校验传输边界。
 */
"limits": OutputTransportConfig;
/**
 * Version of the accepted embedded JSON protocol.
 * 接受的嵌入式 JSON 协议版本。
 */
"protocol_version": number;
/**
 * Runtime operations implemented by the exhaustive dispatcher.
 * 穷尽分发器实现的运行时操作。
 */
"runtime_commands": Array<string>;
} & Record<string, EmbeddedJsonValue>);

/**
 * Live structured failure envelope whose shape also drives SDK generation.
 * 同时驱动 SDK 生成的实际结构化失败信封。
 */
export type OutputErrorResponse = ({
/**
 * Borrowed core error retained until response encoding returns.
 * 保留到响应编码返回的借用核心错误。
 */
"error": OutputEmbeddedError;
/**
 * Accepted embedded protocol version.
 * 接受的嵌入式协议版本。
 */
"protocol_version": number;
/**
 * Exact business-error discriminator.
 * 精确业务错误判别。
 */
"status": OutputErrorStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Immutable description of the exact linked core, usable without a transport or runtime.
 * 精确链接核心的不可变描述，无需传输或运行时即可使用。
 */
export type OutputCoreDescription = ({
/**
 * Exact independent embedded ABI structure version.
 * 精确独立嵌入式 ABI 结构版本。
 */
"abi_structure_version": number;
/**
 * Build input evidence; release manifests bind it to commits and signed artifact checksums separately.
 * 构建输入证据；发布清单另将其关联到提交及签名产物摘要。
 */
"build": OutputEmbeddedBuildIdentity;
/**
 * Implemented semantic features; a name does not grant host permissions.
 * 已实现语义功能；名称不授予宿主权限。
 */
"capabilities": Array<string>;
/**
 * Root command names shared with the exhaustive dispatcher.
 * 与穷尽分发器共享的根命令名称。
 */
"commands": Array<string>;
/**
 * Cargo package version of this exact core.
 * 此精确核心的 Cargo 包版本。
 */
"core_version": string;
/**
 * Version of this independent descriptor format.
 * 此独立描述格式的版本。
 */
"description_version": number;
/**
 * Actually implemented execution backends, excluding reserved unsupported variants.
 * 实际已实现执行后端，不包含预留且不支持的取值。
 */
"execution_backends": Array<OutputExecutionBackend>;
/**
 * Exact embedded JSON protocol version.
 * 精确嵌入式 JSON 协议版本。
 */
"protocol_version": number;
/**
 * Nested command names shared with the exhaustive dispatcher.
 * 与穷尽分发器共享的嵌套命令名称。
 */
"runtime_commands": Array<string>;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootDescribeResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputTransportDescription;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootRuntimeCloseResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRuntimeReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootRuntimeFreeResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRuntimeReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootRuntimeInitializeResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRuntimeReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootRuntimeReserveResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRuntimeReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRootRuntimeStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRuntimeSnapshot;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCallSubmitResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputOperationReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCapabilitiesListResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": Array<OutputCapabilityDescriptor>;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCapabilitiesRegisterResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputRegistrationReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCapabilityForgetResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCapabilityStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputCapabilityRegistrationStatus;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeCapabilityUnregisterResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeHostRequestCompleteResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeHostRequestStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputHostRequestStatus;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeHostRequestsTakeResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": Array<OutputHostRequest>;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeOperationCancelResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": boolean;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeOperationForgetResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeOperationStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputOperationSnapshot;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeOperationWaitResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputOperationSnapshot;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePluginCloseResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePluginForgetResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePluginRegisterResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePluginStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputEmbeddedPluginSnapshot;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePoolCloseResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePoolForgetResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePoolRegisterResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputPoolReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePoolRevokePermissionResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": boolean;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimePoolStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputPoolUsage;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeSessionCloseResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeSessionForgetResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": null;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeSessionOpenResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputSessionReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeSessionStatusResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputEmbeddedSessionSnapshot;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Borrowed success envelope avoids cloning application output during native response publication.
 * 借用成功信封，避免原生响应发布期间克隆应用输出。
 */
export type OutputRuntimeSessionSubmitResponse = ({
/**
 * Single protocol version authority.
 * 唯一协议版本权威。
 */
"protocol_version": number;
/**
 * Borrowed result whose owner lives through serialization.
 * 借用结果，其所有者跨序列化存活。
 */
"result": OutputOperationReceipt;
/**
 * Exact success discriminator.
 * 精确成功判别。
 */
"status": OutputSuccessStatus;
} & Record<string, EmbeddedJsonValue>);

/**
 * Generated wire shape for EmbeddedRootResponseMap.
 * EmbeddedRootResponseMap 的生成线形状。
 */
export type EmbeddedRootResponseMap = {
/**
 * Generated wire shape for describe.
 * describe 的生成线形状。
 */
"describe": OutputRootDescribeResponse;
/**
 * Generated wire shape for runtime_close.
 * runtime_close 的生成线形状。
 */
"runtime_close": OutputRootRuntimeCloseResponse;
/**
 * Generated wire shape for runtime_free.
 * runtime_free 的生成线形状。
 */
"runtime_free": OutputRootRuntimeFreeResponse;
/**
 * Generated wire shape for runtime_initialize.
 * runtime_initialize 的生成线形状。
 */
"runtime_initialize": OutputRootRuntimeInitializeResponse;
/**
 * Generated wire shape for runtime_reserve.
 * runtime_reserve 的生成线形状。
 */
"runtime_reserve": OutputRootRuntimeReserveResponse;
/**
 * Generated wire shape for runtime_status.
 * runtime_status 的生成线形状。
 */
"runtime_status": OutputRootRuntimeStatusResponse;
};

/**
 * Generated wire shape for EmbeddedRuntimeResponseMap.
 * EmbeddedRuntimeResponseMap 的生成线形状。
 */
export type EmbeddedRuntimeResponseMap = {
/**
 * Generated wire shape for call_submit.
 * call_submit 的生成线形状。
 */
"call_submit": OutputRuntimeCallSubmitResponse;
/**
 * Generated wire shape for capabilities_list.
 * capabilities_list 的生成线形状。
 */
"capabilities_list": OutputRuntimeCapabilitiesListResponse;
/**
 * Generated wire shape for capabilities_register.
 * capabilities_register 的生成线形状。
 */
"capabilities_register": OutputRuntimeCapabilitiesRegisterResponse;
/**
 * Generated wire shape for capability_forget.
 * capability_forget 的生成线形状。
 */
"capability_forget": OutputRuntimeCapabilityForgetResponse;
/**
 * Generated wire shape for capability_status.
 * capability_status 的生成线形状。
 */
"capability_status": OutputRuntimeCapabilityStatusResponse;
/**
 * Generated wire shape for capability_unregister.
 * capability_unregister 的生成线形状。
 */
"capability_unregister": OutputRuntimeCapabilityUnregisterResponse;
/**
 * Generated wire shape for host_request_complete.
 * host_request_complete 的生成线形状。
 */
"host_request_complete": OutputRuntimeHostRequestCompleteResponse;
/**
 * Generated wire shape for host_request_status.
 * host_request_status 的生成线形状。
 */
"host_request_status": OutputRuntimeHostRequestStatusResponse;
/**
 * Generated wire shape for host_requests_take.
 * host_requests_take 的生成线形状。
 */
"host_requests_take": OutputRuntimeHostRequestsTakeResponse;
/**
 * Generated wire shape for operation_cancel.
 * operation_cancel 的生成线形状。
 */
"operation_cancel": OutputRuntimeOperationCancelResponse;
/**
 * Generated wire shape for operation_forget.
 * operation_forget 的生成线形状。
 */
"operation_forget": OutputRuntimeOperationForgetResponse;
/**
 * Generated wire shape for operation_status.
 * operation_status 的生成线形状。
 */
"operation_status": OutputRuntimeOperationStatusResponse;
/**
 * Generated wire shape for operation_wait.
 * operation_wait 的生成线形状。
 */
"operation_wait": OutputRuntimeOperationWaitResponse;
/**
 * Generated wire shape for plugin_close.
 * plugin_close 的生成线形状。
 */
"plugin_close": OutputRuntimePluginCloseResponse;
/**
 * Generated wire shape for plugin_forget.
 * plugin_forget 的生成线形状。
 */
"plugin_forget": OutputRuntimePluginForgetResponse;
/**
 * Generated wire shape for plugin_register.
 * plugin_register 的生成线形状。
 */
"plugin_register": OutputRuntimePluginRegisterResponse;
/**
 * Generated wire shape for plugin_status.
 * plugin_status 的生成线形状。
 */
"plugin_status": OutputRuntimePluginStatusResponse;
/**
 * Generated wire shape for pool_close.
 * pool_close 的生成线形状。
 */
"pool_close": OutputRuntimePoolCloseResponse;
/**
 * Generated wire shape for pool_forget.
 * pool_forget 的生成线形状。
 */
"pool_forget": OutputRuntimePoolForgetResponse;
/**
 * Generated wire shape for pool_register.
 * pool_register 的生成线形状。
 */
"pool_register": OutputRuntimePoolRegisterResponse;
/**
 * Generated wire shape for pool_revoke_permission.
 * pool_revoke_permission 的生成线形状。
 */
"pool_revoke_permission": OutputRuntimePoolRevokePermissionResponse;
/**
 * Generated wire shape for pool_status.
 * pool_status 的生成线形状。
 */
"pool_status": OutputRuntimePoolStatusResponse;
/**
 * Generated wire shape for session_close.
 * session_close 的生成线形状。
 */
"session_close": OutputRuntimeSessionCloseResponse;
/**
 * Generated wire shape for session_forget.
 * session_forget 的生成线形状。
 */
"session_forget": OutputRuntimeSessionForgetResponse;
/**
 * Generated wire shape for session_open.
 * session_open 的生成线形状。
 */
"session_open": OutputRuntimeSessionOpenResponse;
/**
 * Generated wire shape for session_status.
 * session_status 的生成线形状。
 */
"session_status": OutputRuntimeSessionStatusResponse;
/**
 * Generated wire shape for session_submit.
 * session_submit 的生成线形状。
 */
"session_submit": OutputRuntimeSessionSubmitResponse;
};
